baseURL = 'https://www.debtplan.app/'
languageCode = 'en-us'
contentDir = "content"
title = 'DebtPlan'

[module]
  replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[params.footer]
  copyright = "© :YEAR: Rev Digital Media, LLC"

[menu]
  [[menu.primary]]
    name = "Docs"
    url = "docs/"
    identifier = "docs"
    weight = 10

  [[menu.primary]]
    name = "FAQs"
    url = "faqs/"
    identifier = "faqs"
    weight = 20

  [[menu.primary]]
    name = "Blog"
    url = "blog/"
    identifier = "blog"
    weight = 30

[services]
  [services.googleAnalytics]
    id = 'G-M01ZH3N95R'
